# Generated by Django 5.0.3 on 2024-03-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_inventoryitem_sku_remove_stockmovement_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
    ]
